name: Staging Deployment via Dispatch

on:
  repository_dispatch:
    types: [deploy-staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy to Staging
      run: |
        echo "Deploying to Staging Environment..."
        # Your deployment script or commands go here
