  name: Staging Deployment via Dispatch

  on:
    workflow_dispatch:
      inputs:
        model_s3_url:
          description: 'Model S3 URL'
          required: true
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Code
        uses: actions/checkout@v2



      - name: Deploy to Staging
        run: |
          echo "Deploying to Staging Environment..."
          # Your deployment script or commands go here
          echo "model_s3_url: ${{ github.event.client_payload.model_s3_url }}"

      - name: Set Model S3 URL
        run: |
          #sed -i 's|value: "s3://new-bucket/new-path/models/v3"|value: "YOUR_NEW_S3_URL"|' path/to/your/rollout-manifest.yaml
          sed -i 's/value: s3:\/\/[^ ]*/value: ${{ github.event.client_payload.model_s3_url }}/g' argocd/argo-rollout.yml
          cat argocd/argo-rollout.yml
